### ISSUE TITLE
migration from allennlp==0.8 to allennlp==1.0

### ISSUE THREAD

**Issue by Mayar2009** [jbarrow/allennlp_tutorial#10]
@jbarrow Hello and thanks for your efforts!
I have code written using allennlp==0.8
I want to upgrade it and continue doing my experiments. Could I do that ? is there any road map to do that?

**Comment by jbarrow** [comment]
So the guide for migrating from 0.9 to 1.0 also covers changing from 0.8 to 1.0, since 0.8 and 0.9 are much more similar to each other than they are to 1.0:

https://github.com/jbarrow/allennlp_tutorial/blob/master/tutorial/A1_Migrating_to_1_0.md

If you run into specific difficulties, though, let me know so I can include that in the migration guide!
